services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: demostrike
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080
