name: Test and build on merge to main
"on":
  push:
    branches:
      - main
jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make install-ci generate test build focus-dependencies
